version: '3.9'

services:
  db:
    image: postgres:14
    container_name: nextcloud-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: raselstr
      POSTGRES_PASSWORD: r283l8tr
    
    networks:
      - production_network

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    expose:
      - "80"
    # ports:
    #   - 8881:80
    restart: always
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - production_network
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: raselstr
      POSTGRES_PASSWORD: r283l8tr
    depends_on:
      - db
    

volumes:
  db_data:
  nextcloud_data:

networks:
  production_network:
    external: true