services:
  db:
    image: postgres:14
    container_name: nextcloud-db
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - production_network

  app:
    image: nextcloud:34-apache
    container_name: nextcloud-app
    restart: always

    expose:
      - "80"

    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      NEXTCLOUD_DOMAIN: ${NEXTCLOUD_DOMAIN}
      NEXTCLOUD_PROTOCOL: ${NEXTCLOUD_PROTOCOL}

    volumes:
      - nextcloud_data:/var/www/html
      - ./config:/opt/config
      - ./entrypoint.sh:/docker-entrypoint-hooks.d/before-starting/10-domain.sh:ro

    depends_on:
      - db

    networks:
      - production_network

volumes:
  db_data:
  nextcloud_data:

networks:
  production_network:
    external: true