version: '3.9'

services:
  db:
    image: postgres:14
    container_name: nextcloud-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: raselstr
      POSTGRES_PASSWORD: R@83l8tr

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - 8881:80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: raselstr
      POSTGRES_PASSWORD: R@83l8tr
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nextcloud-nginx
    restart: always
    ports:
      - 8880:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - app

volumes:
  db_data:
  nextcloud_data:
